### ISSUE TITLE
set gh-pages as the default branch and delete the master branch

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#1]

**Comment by millerdev** [comment]
@MartijnR are you holding off on doing this until you've made more progress, or for some other reason (do you have permission to change the default branch)? I can do it for you if you'd like.

**Comment by MartijnR** [comment]
I don't have permission for this. Yes, please do. Thanks!

On Wed, Oct 15, 2014 at 8:33 AM, Daniel Miller notifications@github.com
wrote:

> @MartijnR https://github.com/MartijnR are you holding off on doing this
> until you've made more progress, or for some other reason (do you have
> permission to change the default branch)? I can do it for you if you'd like.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dimagi/xform-spec/issues/1#issuecomment-59214555.

## 

_Did you know that Enketo Smart Paper has now become the #1 tool for data
collection? Don't fall behind. Use it!_

Enketo https://enketo.org    |    LinkedIn
http://www.linkedin.com/company/enketo-llc    |    GitHub
https://github.com/enketo    |    Twitter https://twitter.com/enketo

**Comment by millerdev** [comment]
Done
