### ISSUE TITLE
External/Artificial instances

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#10]
Current [description of the structure of external instances](http://dimagi.github.io/xform-spec/#secondary-instances---external) links to existing documents describing each type of artificial instance in the BitBucket wiki.

Would you like to keep these separate or merge them inside this XForm documentation (would probably become separate pages) @millerdev, @ctsims?

**Comment by MartijnR** [comment]
I think they should stay separate and let this spec just include how to add a reference to these types of instances.

**Comment by millerdev** [comment]
Sounds good to me. @ctsims, what do you think?

**Comment by millerdev** [comment]
Maybe I'm changing my mind on this. I'm not sure the external links are up to date, and it would be really nice to have them updated. Should that be a separate effort?

Work I'm doing on model iteration (and subsequent spec reading) is the motivating factor.

**Comment by MartijnR** [comment]
To actually update/rewrite/understand them would be a separate effort. However, it's not a problem for me to simply copy the 2.0 CaseDB, Session, Fixture, LedgerDB specs from https://github.com/dimagi/commcare/wiki/CommCare20Specs and place them in separate pages in this repo. So any future updates to these specs would have to be done in this repo (and the wikis removed). Please confirm @ctsims @millerdev 

Related question: https://github.com/dimagi/xform-spec/issues/18

**Comment by ctsims** [comment]
Hey Guys,

Catching back up on all of these links:

I don't think the JavaRosa/OpenRosa standard should be explicit about
_what_ external specs are covered, since that's a platform specific
decision (Platform here being "CommCare" or the like).

I think that CommCare/ODK/Etc should all be responsible for outlining their
own set of supported external instances/how they're loaded/etc.

**Comment by MartijnR** [comment]
So for the table in this section: http://dimagi.github.io/xform-spec/#secondary-instances---external
