### ISSUE TITLE
add uiVersion and name parameters on primary instance

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#13]

**Comment by MartijnR** [comment]
I suspect that the `id` attribute is not supported on the primary instance in CommCare but `name` is.

**Comment by MartijnR** [comment]
Is there a relation between the `name` attribute on the primary instance and `<h:title>`. Which to be considered the title of the form (if they differ)? @ctsims @millerdev

**Comment by ctsims** [comment]
Oof, there's a lot of ambiguity/lack of consensus on this one.

We actually process ~all of the places in the form that people used to use
and one wins by default. I believe it's <title> but we'd be open to
changing that.

**Comment by MartijnR** [comment]
Thanks. 

I think <title> should win.
