### ISSUE TITLE
Document <setvalue>

### ISSUE THREAD

**Issue by millerdev** [dimagi/xform-spec#15]
[Bindings](http://dimagi.github.io/xform-spec/#bindings) are in the spec, but not `<setvalue>`. It would be particularly useful to have documentation for values of the `event` attribute.

Also, would be good to have documentation on the evaluation order of `<setvalue>` and `<bind>` nodes.

**Comment by MartijnR** [comment]
Yes, absolutely. I have a whole bunch of questions about this which are included here: https://github.com/dimagi/xform-spec/issues/4

**Comment by millerdev** [comment]
Ah, sorry for the duplication. As you can see I obviously hadn't read that thoroughly yet. Feel free to close this if it's all captured elsewhere.

**Comment by MartijnR** [comment]
62845b480302369513d0ff1d63ed73fda886c458
