### ISSUE TITLE
namespaces in submissions

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#16]
@ctsims, @millerdev Is it required to include any namespaces in the submission?

E.g. if the meta nodes have the orx: namespace prefix. Should the submission maintain this namespace? I'm guessing strictly speaking yes.... but am hoping that CC doesn't care if these are stripped.

**Comment by ctsims** [comment]
Martijn,

Submissions should definitely maintain namespaces. CommCare, JavaRosa, and
other libraries use the namespaces to outline specific things they need to
process. The metadata should be fine, honestly, but CommCare does model
transactions with structured xml mdoels that we identify by namespace, so
it's pretty key for that.

(I'm working through my backlog and should have more updates on these
points soon. Sorry for the huge gap in my availability there)

-Clayton

**Comment by MartijnR** [comment]
Thanks. I got away with stripping namespaces for too long ;).  I'll add that enketo-incompatibility message to the spec (these messages are hidden and can be shown by clicking the button underneath the ToC or directly going to http://dimagi.github.io/xform-spec/?show-enketo-compatibility=true).

Regarding the backlog: at the moment, I'm somewhat stuck until I get responses. However, from my side that is actually a good thing as I am (also) rather flooded with work. So from my side no worries at all about this!
