### ISSUE TITLE
Add action orx:pollsensor?

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#17]
Just ran across this [here](https://www.commcarehq.org/a/corpora/apps/download/cc3315e9bdb5719c7b57d6ee5b19e797/modules-1/forms-0.xml)

I'm assuming this is a different type of action (like setvalue) that should be added to the [Actions Section](http://dimagi.github.io/xform-spec/#actions).

@ctsims, @millerdev Pollsensor is only used to populate /meta/location, right? Are there any other supported actions apart from pollsensor and setvalue?

**Comment by MartijnR** [comment]
``` xml
<orx:pollsensor event="xforms-ready" ref="/data/meta/location"/>
<bind nodeset="/data/meta/location" type="geopoint"/>
```

**Comment by ctsims** [comment]
@orangejenny Hey: Is there a writeup anywhere about our pollsensor action or anything else we need for Martijn to include it in our xform subset doc?

**Comment by orangejenny** [comment]
@MartijnR Yes, pollsensor is currently only used for /meta/location (and there are no plans to have it do anything else)

**Comment by MartijnR** [comment]
Thanks!

**Comment by lognaturel** [comment]
Heya! ODK is looking at adding an action to support a similar feature. We were thinking of `setlocation` as the name to match XForms action naming. Of course, we do like maintaining compatibility where possible. Is there a particular reason you picked `pollsensor`?

**Comment by orangejenny** [comment]
Hey, no strong reason, `setlocation` sounds as meaningful as `pollsensor`, and I see the point about matching the action name.

**Comment by lognaturel** [comment]
Thanks much, @orangejenny!
