### ISSUE TITLE
Add reference to CaseXML 2.0

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#18]
I could either just write a short description and link to the separate CaseXML spec, or move [this](https://github.com/dimagi/commcare/wiki/CommCare20Specs) here as a separate page.

I won't be able to read/understand the CaseXML spec though (just move it).

@ctsims, @millerdev let me know pls as it means further updates to the spec will need to be done in this repository (and the wikis removed).

**Comment by ctsims** [comment]
I think linking to the spec from the repository is the best plan.

I think of CommCare as being built "On top of" the JavaRosa/OpenRosa XForms
spec, so the specific virtual instance connectors that exist I dont' think
should matter.

I do think that it might be worth outlining how virtual connectors can be
defined, though, to resolve some of the ambiguities we've discussed WRT,
say, how to load things like CSV files.

**Comment by MartijnR** [comment]
Yes, sounds good. An external instance is just an XML document so as long as all the features to query them are defined in the XForm spec, this spec won't have to concern itself with the formats of the different types of external docs.

Wrt to csv data, I believe there is no support for this in CommCare, right? In which case, I should probably leave it out of this spec.

P.S.
Coincidentally, I'll be developing this feature for Enketo this week (and will endeavour to add external XML instance support at the same time). I am planning to just go ahead with what I proposed in the ODK dev thread and introduce the `jr://file-csv` connector: 

`<instance id="fruits" src="jr://file-csv/fruits.csv" />`

You can still correct that in case you'd like to add support for this to CommCare in the future... ODK is not planning to change their current 2 ways of adding external data.
