### ISSUE TITLE
Review XPath functions

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#2]
@millerdev or @ctsims I could have a go at this first by looking at the source code. Could you perhaps point me to the location(s) of the source code for the XPath functions?

**Comment by czue** [comment]
I could be completely wrong but possibly you're looking for this? https://github.com/dimagi/javarosa/blob/master/core/src/org/javarosa/xpath/expr/XPathFuncExpr.java

**Comment by MartijnR** [comment]
yes, thanks!
