### ISSUE TITLE
Bind type namespaces

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#20]
I noticed the "http://www.w3.org/2001/XMLSchema" is used for some bind types. 

Is that the rule for: string, int, boolean, decimal, date, time, and dateTime?

All other types in the default w3.org/2002/xforms namespace?

**Comment by ctsims** [comment]
Martijn,

There's honestly no hard and fast rule, here. The XForms spec kind of declares a lot of the types on its own, and to be straight with you we don't really treat xsd:int any different from "int". I think the default functionality is for that to be in the XForms namespace and that is "correct", but it's not actually enforced on our side (IE: If the default namespace in the doc was something completely random we would still keep parsing "int" as if it was the xforms/xml int)

**Comment by millerdev** [comment]
Follow-up on @ctsims example, our form builder accepts either `xsd:int` or `int`, but always writes `xsd:int`.

**Comment by MartijnR** [comment]
thanks!
