### ISSUE TITLE
Appearances

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#22]
You referred to a table for the supported appearances. Could you link/send me this please?

**Comment by ctsims** [comment]
We'll work on putting that together. Agreed it seems valuable

**Comment by MartijnR** [comment]
To check with Jeremy?

**Comment by ctsims** [comment]
Martijn,

I think this list is up to date?
https://confluence.dimagi.com/display/commcarepublic/Advanced+CommCare+ODK+Formatting
