### ISSUE TITLE
Question lists

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#23]
You referred to missing 'question lists' in the notes. What are these?

**Comment by ctsims** [comment]
This is ODK and CommCare's "field-list" capability, which allows the app to display a set of questions all on one page if the appearance="" attribute of a `<group>` is "field-list".

On CommCare this works with an arbitrary substructure as long as there are no open-ended repeats. IE: If you have a repeat with an XPath count, it'll populate the full repeat in the field list, but if you have a repeat that makes the user manually add/remove elements that won't work

**Comment by MartijnR** [comment]
Thanks. 

> On CommCare this works ... as long as there are no open-ended repeats.

I wonder if we should consider this a implementation deviation due a technical limitation. The desired spec-compliant behaviour would be to display any user-added repeats that are part of a field-list on the same page (as Enketo does in "pages" mode). Repeat creation could be implemented differently (e.g. with a button displayed inside the form and then dynamically inserted into the page). Agreed?

**Comment by millerdev** [comment]
> I wonder if we should consider this a implementation deviation

Seems reasonable to me.
