### ISSUE TITLE
Future: <output> according to XForms spec

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#27]
The might be a deviation with the XForms spec.

Outputs are form controls [according to the XForm spec](http://www.w3.org/TR/xforms/#ui-output), but this is not how it is implemented in Enketo (and ODK I think).

I've only seen it used as a child of a [support element](http://www.w3.org/TR/xforms/#ui-commonelems), i.e. a child of  `<label>` or `<hint>` elements.

Which of these 2 forms are supported in CommCare?

**Comment by millerdev** [comment]
`<output>` elements are only used as a child of a support element such as `<label>`.

**Comment by MartijnR** [comment]
great thanks

**Comment by ctsims** [comment]
Martijn,

We do plan on implementing <output> elements int he future as outlined in
the XForms spec to replace the way we currently use <trigger>s however.

**Comment by MartijnR** [comment]
Ok, thanks. Will keep this open then.
