### ISSUE TITLE
Add Submission section

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#7]
https://bitbucket.org/javarosa/javarosa/wiki/SMSSendingAPI

**Comment by MartijnR** [comment]
@ctsims @millerdev Is the above API supported in CommCare and if so is `<xf:submission>` only used for SMS submissions?

**Comment by ctsims** [comment]
Martijn,

I believe that API is supported by CommCare J2ME but not CommCare Android
due to the lack of atomicity and reliability it introduces.

-Clayton

**Comment by MartijnR** [comment]
Thanks. Should I consider this spec to be for CommCare Android?

Just to be clear, there is no support whatsoever for any usage of `<xf:submission>` in CommCare Android, right?

**Comment by ctsims** [comment]
Yeah, no support for xf:submission at all.

I think we should consider the spec to consist only of the components we
think will be supported long term, and I don't think we currently think
submission is in that list. (we're not opposed to adding it if there is a
compelling reason, though)

-Clayton

**Comment by MartijnR** [comment]
ok, great
