### ISSUE TITLE
Small questions

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#9]
Collection of minor questions @millerdev:

Are the following supported?:
- bind attribute accuracyThreshold (for geopoint capture)
- bind attribute saveIncomplete (to save the record when the user reaches the question)
- XPath function jr:choiceName()

**Comment by millerdev** [comment]
Deferring to @ctsims

**Comment by MartijnR** [comment]
Still to be checked whether jr:choiceName() is supported.

**Comment by ctsims** [comment]
Martijn,

We don't support choiceName(), but do support getting the IText value back from an xpath expression using the jr:itext function on its own.
